services:
  postgres:
    image: postgres
    hostname: postgres
    env_file: .env
    restart: unless-stopped
    networks:
      tduattendance:
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis
    hostname: redis
    networks:
      tduattendance:
    restart: unless-stopped

networks:
  tduattendance:
