---
- hosts: all
  tasks:
    - name: Create TDU Attendance Network
      community.docker.docker_network:
        name: tduattendance_network
    # Postgres
    - name: Deploy TDU Attendance Postgres
      community.docker.docker_container:
        name: TDUAttendancePostgres
        image: postgres
        env_file: ~/TDUAttendance/.env
        hostname: postgres
        volumes:
          - ~/TDUAttendance/data:/var/lib/postgresql/data
        restart_policy: unless-stopped
        networks:
          - tduattendance_network
    # Redis
    - name: Deploy TDU Attendance Redis
      community.docker.docker_container:
        name: TDUAttendanceRedis
        image: redis
        restart_policy: unless-stopped
        hostname: redis
        networks:
          - tduattendance_network
    # Core
    - name: Deploy TDU Attendance Core
      community.docker.docker_container:
        name: TDUAttendanceCore
        image: ghcr.io/sebasptsch/tduattendance
        env_file: ~/TDUAttendance/.env
        ports:
          - 6300:3000
        restart_policy: unless-stopped
        pull: true
        networks:
          - tduattendance_network
